# Generated by Django 4.2.13 on 2024-06-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('nivelEducativo', models.CharField(max_length=100)),
                ('familiares', models.CharField(max_length=500)),
                ('familiaresDetalles', models.CharField(max_length=500)),
                ('personal1', models.CharField(max_length=500)),
                ('personal1Detalles', models.CharField(max_length=500)),
                ('personal2', models.CharField(max_length=500)),
                ('personal3', models.CharField(max_length=500)),
                ('personal4', models.CharField(max_length=500)),
                ('familiares1', models.CharField(max_length=500)),
                ('familiares2', models.CharField(max_length=500)),
                ('familiares2Detalles', models.CharField(max_length=500)),
                ('familiares3', models.CharField(max_length=500)),
                ('pesem1', models.CharField(max_length=500)),
                ('pesem2', models.CharField(max_length=500)),
                ('pesem3', models.CharField(max_length=500)),
                ('solidario1', models.CharField(max_length=500)),
                ('solidario2', models.CharField(max_length=500)),
                ('solidario3', models.CharField(max_length=500)),
                ('solidario4', models.CharField(max_length=500)),
                ('coovitel1', models.CharField(max_length=500)),
                ('coovitel2', models.CharField(max_length=500)),
                ('coovitel3', models.CharField(max_length=500)),
                ('coovitel3Detalles', models.CharField(max_length=500)),
                ('coovitel4', models.CharField(max_length=500)),
                ('coovitel5', models.CharField(max_length=500)),
                ('coovitel6', models.CharField(max_length=500)),
                ('sugerencia1', models.CharField(max_length=500)),
                ('sugerencia2', models.CharField(max_length=500)),
            ],
        ),
    ]
