# Generated by Django 4.2.13 on 2024-06-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_dirigente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
