# Generated by Django 4.2.13 on 2024-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_alter_asociado_cedula_alter_colaborador_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
